### ISSUE TITLE
cargo local-registry --sync Cargo.lock vendor/ fails when .cargo/config is present

### ISSUE THREAD

**Issue by idubrov** [alexcrichton/cargo-local-registry#79]
`cargo local-registry --sync Cargo.lock vendor/` fails when `.cargo/config` overriding the crates-io is present:

```toml
[source.crates-io]
registry = 'https://github.com/rust-lang/crates.io-index'
replace-with = 'local-registry'

[source.local-registry]
local-registry = "vendor"
```

Potentially, something similar to [this code](https://github.com/alexcrichton/cargo-vendor/blob/9dd97841687e7b072a4edbb0e789be926861be70/src/main.rs#L78) in `cargo-vendor` is needed?
